MONGO_DB_NAME = 'release_info'
FIX_VERSIONS_CACHE_EXPIRE_AFTER = 300
BACKEND_HOST = 'http://localhost:8000'
JIRA_USER = 'NGlebanov'
JIRA_TOKEN = 'FDCXSFBLQ4KACTBULV5R3ESCACRXJJG5XYSLNYESFTGMLXFNF2VFTMQMSNO7WK5HWRBZQY4F7SXSDXIRVFDPEQGMOBR3HS55PBCSMG56ARPT2OUFAFP5RXDI23KLARHZ'
JIRA_URL = 'https://jira.server.ru'